global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'whoknows-app'
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets: ['mathiasmortensen.dk']
        labels:
          instance: 'tivieserver'

  - job_name: 'node-exporter'
    scheme: https
    metrics_path: /node-metrics
    static_configs:
      - targets: ['mathiasmortensen.dk']
        labels:
          instance: 'tivieserver'
