global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-app'
    scheme: https
    metrics_path: /node-metrics
    static_configs:
      - targets: ['mathiasmortensen.dk']
        labels:
          instance: 'tivieserver'

  - job_name: 'ruby-app'
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets: ['mathiasmortensen.dk']
        labels:
          instance: 'tivieserver'
